language: node_js
os: linux
dist: xenial
node_js:
  - 12.18.2
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: main
