language: node_js
os: linux
dist: xenial
cache:
  directories:
    - node_modules
node_js:
  - 12.18.2
install:
  - yarn install
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: gh-pages
  on:
    branch: main
